### ISSUE TITLE
Leniency not abided by on fresh install

### ISSUE THREAD

**Issue by loopy3025** [mglaman/composer-drupal-lenient#13]
This is a great plugin. Thanks for working on it.

I've noticed, however, that the plugin is ignored sometimes. After trying it out, I believe it only happens when I delete the vendor folder and the composer.lock, then try to composer install. When I do this, Composer does not abide by leniency and tries to install the packages with their old Drupal dependencies intact.

To reproduce:
- composer.json with d10 installed and a d9 module with leniency set
- delete composer.lock and the /vendor folder
- composer install

**Comment by joeparsons** [comment]
Looked at the composer documentation.  Seems like the only event that happens before a lock file is created is the `pre-operations-exec` installer event but that can only be used by plugins that are installed globally 😞:

>**[Installer Events](https://getcomposer.org/doc/articles/scripts.md#installer-events)**
>- pre-operations-exec: occurs before the install/upgrade/.. operations are executed when installing a lock file. Plugins that need to hook into this event will need to be installed globally to be usable, as otherwise they would not be loaded yet when a fresh install of a project happens.

**Comment by mglaman** [comment]
Ah, that makes sense. How common is this scenario to blow away the lock file?

**Comment by mglaman** [comment]
Oh, wait. We can integrate with that hook. This package can be setup to be installed globally or per project, then.

**Comment by mglaman** [comment]
@joeparsons can you test something for me? From the results of https://github.com/mglaman/composer-drupal-lenient/pull/18, you can add this plugin globally, and it'll "just work."

```shell
composer global config --no-plugins allow-plugins.mglaman/composer-drupal-lenient true
composer global require mglaman/composer-drupal-lenient
```
