### ISSUE TITLE
Conflict with 

### ISSUE THREAD

**Issue by damienmckenna** [mglaman/composer-drupal-lenient#15]
I'm trying to add [webform_migrate](https://www.drupal.org/project/webform_migrate) to a D10 site and have hit an odd problem.

I've added drupal/webform:^6.2.0@beta to the site, that bit is fine.

webform_migrate doesn't list any dependencies in its Composer file, so the Drupal packagist adds that info.

    $ composer show drupal/webform_migrate -a
    name     : drupal/webform_migrate
    descrip. : Migration routines from d6 & d7 webform to d8 webform
    keywords : Drupal
    versions : 1.x-dev, 1.2.0, 1.1.0, 1.0.0, 1.0.0-alpha2, 1.0.0-alpha1, dev-1.x
    type     : drupal-module
    license  : GNU General Public License v2.0 or later (GPL-2.0+) (OSI approved) https://spdx.org/licenses/GPL-2.0+.html#licenseText
    homepage : https://www.drupal.org/project/webform_migrate
    source   : [git] https://git.drupalcode.org/project/webform_migrate.git 629161c6dd4f806f2313b9dc9be257d0c55d7284
    dist     : []  
    names    : drupal/webform_migrate
    
    support
    source : http://cgit.drupalcode.org/webform_migrate
    issues : http://drupal.org/project/issues/webform_migrate
    
    requires
    drupal/webform *
    drupal/webform_node *
    drupal/core ^8.8 || ^9

As you can see, it doesn't care what release of Webform is provided.

webform_migrate doesn't have a D10 release, so I try to add it using the lenient plugin:

    $ composer config --merge --json extra.drupal-lenient.allowed-list '["drupal/webform_migrate"]'

Then I try adding it as normal:

    $ ddev composer require drupal/webform_migrate:dev-1.x
    ./composer.json has been updated
    Running composer update drupal/webform_migrate
    Gathering patches for root package.
    Loading composer repositories with package information
    Updating dependencies
    Info from https://repo.packagist.org: #StandWithUkraine
    Your requirements could not be resolved to an installable set of packages.
    
      Problem 1
        - drupal/webform_node[5.9.0, ..., 5.13.0] require drupal/core ^8.7.7 || ^9 -> found drupal/core[8.7.7, ..., 8.9.20, 9.0.0, ..., 9.5.9] but the package is fixed to 10.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
        - drupal/webform_node[5.0.0, ..., 5.15.0] require drupal/core ^8 -> found drupal/core[8.0.0, ..., 8.9.20] but the package is fixed to 10.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
        - drupal/webform_node[5.16.0, ..., 5.31.0] require drupal/core ^8.8 -> found drupal/core[8.8.0, ..., 8.9.20] but the package is fixed to 10.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
        - drupal/webform_node[6.0.0, ..., 6.1.4] require drupal/core ^8.8 || ^9 -> found drupal/core[8.8.0, ..., 8.9.20, 9.0.0, ..., 9.5.9] but the package is fixed to 10.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
        - drupal/webform_migrate dev-1.x requires drupal/webform_node * -> satisfiable by drupal/webform_node[5.0.0, ..., 5.31.0, 6.0.0, ..., 6.1.4].
        - Root composer.json requires drupal/webform_migrate dev-1.x -> satisfiable by drupal/webform_migrate[dev-1.x].
    
    Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
    
    Installation failed, reverting ./composer.json and ./composer.lock to their original content.
    composer [require drupal/webform_migrate:dev-1.x] failed, composer command failed: exit status 2. stderr=

Working backwards.. it's saying that it can't install webform_migrate because it requires `webform_node *`, which is included in Webform, and which is satisfiable by one of the stable releases of Webform. So why won't it accept the release of Webform Node that's already installed?

**Comment by damienmckenna** [comment]
Ducktyping being what it is, I worked out two possible solutions while writing out the issue:

1. Add webform and webform_node to the lenient list.
2. Manually add webform_node:dev-6.2.x in addition to webform:dev-6.2.x.

The problem seems to stem from webform_migrate not listing webform in its composer.json file.

**Comment by damienmckenna** [comment]
I opened an issue form Webform Migrate to fix its composer file, as that's ultimately the source of the problem: https://www.drupal.org/project/webform_migrate/issues/3361646

**Comment by mglaman** [comment]
Closing – this was a subpackage/metapackage issue. The other fix may have been to also add Webform's submodules to the lenient list.
