### ISSUE TITLE
Does this work for upgrades?

### ISSUE THREAD

**Issue by ethanteague** [mglaman/composer-drupal-lenient#16]
Wondering if I'm missing something - when I require this package and then add items to my composer.json file ala
`"drupal-lenient": {
            "allowed-list": ["drupal/tb_megamenu", "drupal/views_filter_populate", "drupal/bootstrap_styles", "drupal/dbug"]
        }` 
I'm still seeing the same version incompatibility messages when I run `composer update` (trying to upgrade core from 9 to 10).

**Comment by mglaman** [comment]
Weird. So on a plain `composer update` it's being ignored?

Can you provide your Composer version as well

**Comment by ethanteague** [comment]
> Weird. So on a plain `composer update` it's being ignored?

It is

> Can you provide your Composer version as well

2.5.5

**Comment by chicodasilva** [comment]
I am having the same issue. I want to upgrade to D10 and these modules are in the list:
```
        "drupal-lenient": {
            "allowed-list": ["drupal/business_rules", "drupal/captcha", "drupal/linkit"]
        }
```

My composer version:
**Composer version 2.5.5 2023-03-21 11:50:05**

**Comment by mglaman** [comment]
Actually, can everyone having issues try installing this plugin globally?

```shell
composer global config --no-plugins allow-plugins.mglaman/composer-drupal-lenient true
composer global require mglaman/composer-drupal-lenient
```

It's not the greatest idea since the plugin will run on projects not directly using it. But it could resolve any quirks if Composer doesn't consider the plugin installed while processing the command.

**Comment by attheshow** [comment]
It was working OK for me last month without running it globally. This month I had to. I'm not sure what changed honestly, but thought I would at least share my experience. 😊

**Comment by mglaman** [comment]
Running it globally is a viable workaround when things get weird. It's documented on the project's README about using a global installation to work around this. I'll close the issue, as I don't think anything else can be done.

Thanks for following up with your experience!
