### ISSUE TITLE
syntax error, unexpected 'private' (T_PRIVATE), expecting variable (T_VARIABLE) 

### ISSUE THREAD

**Issue by IRL-eqbal** [mglaman/composer-drupal-lenient#20]
I'm encountering an error on the server while trying to install the package. However, in the local environment, everything is working fine, and there are no such issues.

**Issue**
- Installing mglaman/composer-drupal-lenient (1.0.3): Extracting archive
    Install of mglaman/composer-drupal-lenient failed
In PackageRequiresAdjuster.php line 22:
                                                                               
  [ParseError]                                                                 
  syntax error, unexpected 'private' (T_PRIVATE), expecting variable (T_VARIA  
  BLE) 

**Composer version**

```
Composer version 2.5.8 
```

**Comment by mglaman** [comment]
Your target environment isn't using PHP 8.1 which this package requires. You must have used it locally so more then just this package will break.
