### ISSUE TITLE
Illegal byte sequence with 1.0.4

### ISSUE THREAD

**Issue by xpersonas** [mglaman/composer-drupal-lenient#29]
**Describe the bug**
I'm unable to install the 1.0.4 version. I'm getting an `Illegal byte sequence` error when extracting. Reverting to 1.0.3 works fine.

```
Failed to extract mglaman/composer-drupal-lenient: (50) '/usr/bin/unzip' -qq '/Users/name/Sites/work/sic-website/vendor/composer/tmp-542d0dc73d8c36760538a2b2b43f4635' -d '/Users/name/Sites/work/sic-website/vendor/composer/1445a2cc'
error:  cannot create /Users/name/Sites/work/sic-website/vendor/composer/1445a2cc/mglaman-composer-drupal-lenient-6f9e03f/.github/ISSUE_TEMPLATE/�?��-bug-report.md
        Illegal byte sequence
```

**Composer version**
```
Composer version 2.5.4 2023-02-15 13:10:06
```

**Comment by mglaman** [comment]
Try clearing your composer cache. I have no control over the packaging as Packagist reads from GitHub archives, and no one else has reported this yet.

**Comment by andybroomfield** [comment]
I had this issue to, `composer clear-cache` resolved it for me.

**Comment by mglaman** [comment]
I'll close. I have no idea why, but I can't control the packaging and such.
