### ISSUE TITLE
Allow leniency for *all* packages?

### ISSUE THREAD

**Issue by lal65** [mglaman/composer-drupal-lenient#31]
As a user that's trying to test some bleeding edge 11.x issues against a..."well tenured" real project, I'd like to be able to install 11.x along-side of 80 modules without needing to allow-list them all.

Is there a way to do that?  Thanks!

**Comment by mglaman** [comment]
There is not. There could be a new flag. That seems easier than adding wildcard support. 

```
 extra.drupal-lenient.allow-all: true
```

Something like this. If set, all `drupal/` packages modified

**Comment by gitressa** [comment]
Fantastic @mglaman, thanks! I tried it and it works well. I just added a few Drupal 10 modules with the new flag. 

**Preparation**
1. Install  [Backward Compatibility](https://www.drupal.org/project/backward_compatibility)
2. Set the `allow-all` flag to `true`

Get and install three modules, not yet Drupal 11 ready:

```
$ composer require drupal/webform:6.2.x-dev@dev \
                   drupal/video_embed_field:2.x-dev@dev \
                   drupal/xmlsitemap:1.x-dev@dev

$ drush install webform video_embed_field xmlsitemap
 [success] Module webform has been installed. (Help - Permissions - Configure)
 [success] Module video_embed_field has been installed. (Help - Permissions)
 [success] Module xmlsitemap has been installed. (Help - Permissions - Configure)
```
