### ISSUE TITLE
Emoji in file name causes Dropbox sync to fail

### ISSUE THREAD

**Issue by A-Kun** [mglaman/composer-drupal-lenient#33]
There's an emoji in the file name `🐞-bug-report.md`. Dropbox does not seem to like this and flags this file as a sync issue:
<img width="668" alt="pngout" src="https://github.com/user-attachments/assets/1f0de1fc-55be-46c4-bd51-a25f2c2c22d9">

**Comment by mglaman** [comment]
Fixed with https://github.com/mglaman/composer-drupal-lenient/releases/tag/1.0.6
